---
- name: install packages and updated
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items:
     - apache2
     - git
     - ntp
     - iptables
     - wget
  tags: configuration

- name: Configure dns
  template: src=resolv.conf
            dest=/etc/resolv.conf
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Configure hosts files
  template: src=hosts
            dest=/etc/hosts
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Configure repository debian
  template: src=sources.list
            dest=/etc/apt/sources.list
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Disable Debian services from boot startup
  service: name={{ item }}
           enabled=no
  with_items:
      - avahi-daemon
      - firewalld
      - chronyd
  tags: configuration

- name: Configure ntp
  template: src=ntp.conf
            dest=/etc/ntp.conf
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Set UTC date
  command: timedatectl set-timezone UTC
  tags: configuration

- name: Delete requiretty from sudoers to be able to use systemd
  lineinfile: dest=/etc/sudoers
              state=absent
              line="Defaults    requiretty"
  tags: configuration

- name: Ensure some services are started and enabled
  service:  name={{ item.service }}
            enabled={{ item.enabled }}
            state={{ item.state }}
  with_items:
      - { service: 'ntp', enabled: 'yes', state: 'started' }
      - { service: 'apache2', enabled: 'yes', state: 'started' }
  tags: configuration

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2
  tags: configuration

- name: Configure virtualhost of Brazil
  template: src=virtualhost.conf
            dest=/etc/apache2/sites-available/
            mode=0644
            owner=root
            group=root
  with_items: br
  notify: restart apche2
  tags: brazil

- name: Configure virtualhost of Chile
  template: src=virtualhost.conf
            dest=/etc/apache2/sites-available/
            mode=0644
            owner=root
            group=root
  with_items: ch
  notify: restart apache2
  tags: chile

#- name: apache2 listen on port {{ http_port }}
#  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
#  notify:
#    - restart apache2
#
#- name: apache2 virtualhost on port {{ http_port }}
#  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
#  notify:
#    - restart apache2

- name: a2ensite virtualhost.conf
  command: a2ensite virtualhost.conf
  args:
    creates: /etc/apache2/sites-enabled/virtualhost.conf
  notify:
    - restart apache2
  tags: configuration

- name: clone basic html template
  git: repo=https://github.com/do-community/ansible-apache-tutorial.git dest=/var/www/example.com update=no
  tags: configuration