---
- name: install packages and updated
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items:
     - apache2
     - git
     - ntp
     - iptables-persistent
     - wget
     - gcc
  tags: configuration

- name: Configure dns
  template: src=resolv.conf
            dest=/etc/resolv.conf
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Configure hosts files
  template: src=hosts
            dest=/etc/hosts
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Configure repository debian
  template: src=sources.list
            dest=/etc/apt/sources.list
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Configure iptables for node services
  copy: src=iptables/iptables
        dest=/etc/iptables/rules.v4
        owner=root
        group=root
  tags: configuration

- name: Disable Debian services from boot startup
  service: name={{ item }}
           enabled=no
  with_items:
      - avahi-daemon
      - firewalld
      - chronyd
  tags: configuration

- name: Configure ntp
  template: src=ntp.conf
            dest=/etc/ntp.conf
            mode=0644
            owner=root
            group=root
  tags: configuration

- name: Set UTC date
  command: timedatectl set-timezone UTC
  tags: configuration

- name: Delete requiretty from sudoers to be able to use systemd
  lineinfile: dest=/etc/sudoers
              state=absent
              line="Defaults    requiretty"
  tags: configuration

- name: Ensure some services are started and enabled
  service:  name={{ item.service }}
            enabled={{ item.enabled }}
            state={{ item.state }}
  with_items:
      - { service: 'ntp', enabled: 'yes', state: 'started' }
      - { service: 'apache2', enabled: 'yes', state: 'started' }
  tags: configuration

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2
  tags: configuration

- name: Configure logrotate for services
  copy: src=logrotate/{{ item }}
        dest=/etc/logrotate.d/
        owner=root
        group=root
  with_items:
      - apache2
  tags: configuration

- name: Make sure log dir exists and it is property of the run user
  file: path=/var/log/apache2
        state=directory
        owner=root
        group=root
        mode=775
  tags: configuration

- name: Make Virtualhost mutable
  shell: chattr -i /etc/apache2/sites-available/virtualhost.conf
  changed_when: False
#  when: config_status.stat.exists == True
  tags: configuration

- name: Configure virtualhost of Brazil
  template: src=virtualhost.conf
            dest=/etc/apache2/sites-available/
            mode=0644
            owner=root
            group=root
  with_items: br
  notify: restart apache2
  tags: brazil

- name: Configure virtualhost of Chile
  template: src=virtualhost.conf
            dest=/etc/apache2/sites-available/
            mode=0644
            owner=root
            group=root
  with_items: ch
  notify: restart apache2
  tags: chile

- name: Make virtualhost inmutable
  shell: chattr +i /etc/apache2/sites-available/virtualhost.conf
  changed_when: False
  tags: configuration

- name: Configure ports of Brazil
  template: src=ports.conf
            dest=/etc/apache2/ports.conf
            mode=0644
            owner=root
            group=root
  with_items: br
  notify: restart apache2
  tags: brazil

- name: Configure ports of Chile
  template: src=ports.conf
            dest=/etc/apache2/ports.conf
            mode=0644
            owner=root
            group=root
  with_items: ch
  notify: restart apache2
  tags: chile

- name: a2ensite virtualhost.conf
  command: a2ensite virtualhost.conf
  args:
    creates: /etc/apache2/sites-enabled/virtualhost.conf
  notify:
    - restart apache2
  tags: configuration

- name: clone basic html template
  git: repo=https://github.com/do-community/ansible-apache-tutorial.git dest=/var/www/example.com update=no
  tags: configuration